[project]
name = 'ups-solar-App'
description = 'Professional UPS and Solar Service Marketplace Platform with Escrow System'
authors = ['UPS Solar Team']
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.ups-solar-App]
path = 'contracts/ups-solar-App.clar'
clarity_version = 3
epoch = 'latest'

[contracts.roles]
path = 'contracts/roles.clar'
clarity_version = 3
epoch = 'latest'

[contracts.escrow]
path = 'contracts/escrow.clar'
clarity_version = 3
epoch = 'latest'

[contracts.service-marketplace]
path = 'contracts/service-marketplace.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = true

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
